<wsdl:definitions name="ConcatReferenceService" targetNamespace="http://xmlns.oracle.com/Case6AppOSB/Case6ProjectOSB/ConcatReferenceService" xmlns:tns="http://xmlns.oracle.com/Case6AppOSB/Case6ProjectOSB/ConcatReferenceService" xmlns:inp1="http://TargetNamespace.com/ConcatNameExposeService_ConCatOpr_request" xmlns:inp2="http://TargetNamespace.com/ConcatNameExposeService_ConCatOpr_response" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="ConcatReferenceService">
        <plnk:role name="ConcatReferenceServiceProvider" portType="tns:ConcatReferenceService_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://TargetNamespace.com/ConcatNameExposeService_ConCatOpr_request" schemaLocation="req_concat_service_desc.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://TargetNamespace.com/ConcatNameExposeService_ConCatOpr_response" schemaLocation="resp_concat_service_desc.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="ConCatOpr_inputMessage">
        <wsdl:part name="request" element="inp1:Root-Element"/>
    </wsdl:message>
    <wsdl:message name="ConCatOpr_outputMessage">
        <wsdl:part name="reply" element="inp2:Root-Element"/>
    </wsdl:message>
    <wsdl:portType name="ConcatReferenceService_ptt">
        <wsdl:operation name="ConCatOpr">
            <wsdl:input message="tns:ConCatOpr_inputMessage"/>
            <wsdl:output message="tns:ConCatOpr_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ConcatReferenceService_ptt-binding" type="tns:ConcatReferenceService_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ConCatOpr">
            <soap:operation soapAction="ConCatOpr"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>